# Generated by Django 2.1.5 on 2019-01-30 13:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPickUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_thing', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(1, 'clothes-to-use'), (2, 'clothes-useless'), (3, 'toys'), (4, 'books'), (5, 'other')], max_length=16), size=None)),
                ('quantity', models.IntegerField()),
                ('localization', models.IntegerField(choices=[(1, 'Warszawa'), (2, 'Wrocław'), (3, 'Poznań'), (4, 'Gdańsk')])),
                ('pick_up_phone_number', models.CharField(max_length=16)),
                ('pick_up_date', models.DateField()),
                ('pick_up_hour', models.TimeField()),
                ('pick_up_address_street', models.CharField(max_length=256)),
                ('pick_up_address_city', models.CharField(max_length=256)),
                ('pick_up_address_post_code', models.CharField(max_length=256)),
                ('notes', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('localization', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(1, 'Warszawa'), (2, 'Wrocław'), (3, 'Poznań'), (4, 'Gdańsk')], max_length=16), size=None)),
                ('help_for', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(1, 'children'), (2, 'mothers'), (3, 'homeless'), (4, 'disabled'), (5, 'old')], max_length=16), size=None)),
                ('address_street', models.CharField(max_length=256)),
                ('address_city', models.CharField(max_length=256)),
                ('address_post_code', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='newpickup',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Organization'),
        ),
        migrations.AddField(
            model_name='newpickup',
            name='who_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
